In [1]:
import numpy as np
from utils import batch_iter
from vocab import Vocab
import torch
import torch.nn as nn
import nltk

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/shaozhetao/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:

# unsqueeze dec_hidden from dec_hidden=(b, h) to dec_hidden=(b, h, 1）
# unsqueeze means add a new dim of 1 to the index
unsqueeze_dec_hidden = dec_hidden.unsqueeze(2)

e_t = torch.bmm(enc_hiddens_proj, unsqueeze_dec_hidden).squeeze(2)  # enc_hiddens_proj=(b, src_len, h)

In [2]:
b, h = 4, 9
dec_hidden = torch.randn(b, h)

In [3]:
unsqueeze_dec_hidden = dec_hidden.unsqueeze(2)

In [4]:
unsqueeze_dec_hidden.shape

torch.Size([4, 9, 1])

In [6]:
enc_hiddens_proj=torch.randn(b, 3, h)

In [7]:
enc_hiddens_proj.shape

torch.Size([4, 3, 9])

In [9]:
torch.bmm(enc_hiddens_proj, unsqueeze_dec_hidden).shape

torch.Size([4, 3, 1])

In [2]:
def read_corpus(file_path, source):
    # Understood
    """ Read file, where each sentence is dilineated by a `\n`.
    @param file_path (str): path to file containing corpus
    @param source (str): "tgt" or "src" indicating whether text
        is of the source language or target language
    """
    data = []
    for line in open(file_path):
        sent = nltk.word_tokenize(line)
        # only append <s> and </s> to the target sentence
        if source == 'tgt':
            sent = ['<s>'] + sent + ['</s>']
        data.append(sent)

    return data

In [115]:
# BATCH_SIZE = 5
# EMBED_SIZE = 4
# HIDDEN_SIZE = 3
# DROPOUT_RATE = 0.0
# seed = 1234

In [4]:
# Load training data & vocabulary
train_data_src = read_corpus('./sanity_check_en_es_data/train_sanity_check.es', 'src')
train_data_tgt = read_corpus('./sanity_check_en_es_data/train_sanity_check.en', 'tgt')
train_data = list(zip(train_data_src, train_data_tgt))

for src_sents, tgt_sents in batch_iter(train_data, batch_size=BATCH_SIZE, shuffle=True):
    src_sents = src_sents
    tgt_sents = tgt_sents
    break
vocab = Vocab.load('./sanity_check_en_es_data/vocab_sanity_check.json') 

In [79]:
char2id = json.load(open('./sanity_check_en_es_data/char_vocab_sanity_check.json', 'r'))

In [81]:
len(char2id)

30

In [90]:
char2id

{'<pad>': 0,
 '{': 1,
 '}': 2,
 '<unk>': 3,
 'a': 4,
 'b': 5,
 'c': 6,
 'd': 7,
 'e': 8,
 'f': 9,
 'g': 10,
 'h': 11,
 'i': 12,
 'j': 13,
 'k': 14,
 'l': 15,
 'm': 16,
 'n': 17,
 'o': 18,
 'p': 19,
 'q': 20,
 'r': 21,
 's': 22,
 't': 23,
 'u': 24,
 'v': 25,
 'w': 26,
 'x': 27,
 'y': 28,
 'z': 29}

### Let's do a test

In [128]:
e_char = 50

In [129]:
char_pad_token_idx = char2id['<pad>']

In [130]:
charEmbedding = nn.Embedding(95, e_char, char_pad_token_idx)

In [131]:
output.shape#.torch.Size([8, 4, 12]) sen_len, batch, m_word

torch.Size([8, 4, 12])

###  Getting output, now CNN

In [132]:
x = charEmbedding(output)

tensor([[[-1.2049, -1.4665,  2.5728,  ...,  0.1126, -0.9009,  0.5060],
         [ 0.6264, -0.1826,  0.1747,  ..., -1.1034, -1.0896,  1.3063],
         [-0.4064,  0.8771,  0.7678,  ..., -0.0860,  2.1354, -1.2489],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[-1.2049, -1.4665,  2.5728,  ...,  0.1126, -0.9009,  0.5060],
         [ 0.0515,  0.9324, -0.6278,  ...,  0.9818,  0.4140,  0.7677],
         [-1.3281, -0.4089,  0.5356,  ..., -1.4368,  0.9211, -0.8499],
         ...,
         [ 1.4147,  0.9576, -0.2676,  ...,  0.6742,  0.4508, -0.5939],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[-1.2049, -1.4665,  2.5728,  ...,  0.1126, -0.9009,  0.5060],
         [ 0.6264, -0.1826,  0.1747,  ..., -1

In [143]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CS224N 2019-20: Homework 5
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class CNN(nn.Module):

    # Remember to delete the above 'pass' after your implementation
    ### YOUR CODE HERE for part 1g
    def __init__(self, e_char, filters, padding=1, kernel_size=5):
        super(CNN, self).__init__()

        self.e_char = e_char
        self.m_word = m_word
        self.filters = filters
        self.padding = padding
        self.k = kernel_size

        self.conv1d = None
        self.maxpool = None

        self.conv1d = nn.Conv1d(
            in_channels=self.e_char,
            out_channels=self.filters,
            kernel_size=self.k,
            stride=1,
            padding=self.padding,
            padding_mode='zeros',
            bias=True
        )



    def forward(self, xemb: torch.Tensor):
        # xemb #shape (batch, m_word, e_char)
        # xreshape #shape (batch, e_char, m_word)
        # W #shape (filter, e_char, k)

        m_word = xemb.shape[-2]
        x_reshaped = xemb.permute(0, 1, 3, 2)
        x_conv = self.conv1d(x_reshaped)
        x_conv = F.relu(x_conv)

        maxpool = nn.MaxPool1d(kernel_size=m_word + 2 * self.padding - self.k + 1)
        x_conv_out = maxpool(x_conv)

        return x_conv_out

    ### END YOUR CODE



In [144]:
cnn = CNN(e_char, filters=10)

In [145]:
x.shape[-2]

12

In [148]:
y = x.permute(0, 1, 3, 2)

In [149]:
y.shape

torch.Size([8, 4, 50, 12])

In [154]:
xx = torch.randn(2,4,6)

In [155]:
xx.shape

torch.Size([2, 4, 6])

In [170]:
xx = torch.randn(50, 30, 21)

In [171]:
xx.shape

torch.Size([50, 30, 21])

In [172]:
ccc = nn.Conv1d(
    in_channels=30,
    out_channels=3,
    kernel_size=5,
    stride=1,
    padding=1,
    padding_mode='zeros',
    bias=True
)

In [176]:
yy = torch.randn(50,3,1)

In [ ]:
yy.

In [175]:
w_proj = nn.Linear(3, 3, bias=True)

In [177]:
w_proj(yy)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (150x1 and 3x3)

In [160]:
maxpool = nn.MaxPool1d(5)

In [161]:
maxpool(xx)

tensor([[[ 0.9172],
         [-0.0972],
         [ 1.2620],
         [ 1.0838]],

        [[ 1.2783],
         [ 1.4607],
         [ 1.5482],
         [ 0.6417]]])

In [6]:
def pad_sents_char(sents, char_pad_token):
    """ Pad list of sentences according to the longest sentence in the batch and longest words in all sentences.
    @param sents (list[list[list[int]]]): list of sentences, result of `words2charindices()`
        from `vocab.py`
    @param char_pad_token (int): index of the character-padding token
    @returns sents_padded (list[list[list[int]]]): list of sentences where sentences/words shorter
        than the max length sentence/word are padded out with the appropriate pad token, such that
        each sentence in the batch now has same number of words and each word has an equal
        number of characters
        Output shape: (batch_size, max_sentence_length, max_word_length)
    """

    sents_padded = []
    max_word_length = max(len(w) for s in sents for w in s )
    max_sent_len = max(len(s) for s in sents)
    batch_size = len(sents)

    for k in range(batch_size):
        sentence = sents[k]
        sent_padded = []

        for w in sentence:
            data = [c for c in w] + [char_pad_token for _ in range(max_word_length-len(w))]
            if len(data) > max_word_length:
                data = data[:max_word_length]
            sent_padded.append(data)

        sent_padded = sent_padded[:max_sent_len] + [[char_pad_token]*max_word_length] * max(0, max_sent_len - len(sent_padded))
        sents_padded.append(sent_padded)

    return sents_padded

In [7]:
# xx = pad_sents_char(src_sents, '<char>')
# xx
char_list = list(
            """ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789,;.!?:'\"/\\|_@#$%^&*~`+-=<>()[]""")
char2id = dict()  # Converts characters to integers
char2id['∏'] = 0  # <pad> token
char2id['{'] = 1  # start of word token
char2id['}'] = 2  # end of word token
char2id['Û'] = 3  # <unk> token
for i, c in enumerate(char_list):
    char2id[c] = len(char2id)
char_pad = char2id['∏']
char_unk = char2id['Û']
start_of_word = char2id["{"]
end_of_word = char2id["}"]
assert start_of_word + 1 == end_of_word

In [70]:
sentences = [['Human', ':', 'What', 'do', 'we', 'want', '?'], ['Computer', ':', 'Natural', 'language', 'processing', '!'], ['Human', ':', 'When', 'do', 'we', 'want', 'it', '?'], ['Computer', ':', 'When', 'do', 'we', 'want', 'what', '?']]
sentence_length = 8
BATCH_SIZE = 4
word_length = 12
vocabEntry = VocabEntry()
output = vocabEntry.to_input_tensor_char(sentences, 'cpu')

In [69]:
from collections import Counter
from docopt import docopt
from itertools import chain
import json
import torch
from typing import List
from utils import read_corpus, pad_sents, pad_sents_char


class VocabEntry(object):
    """ Vocabulary Entry, i.e. structure containing either
    src or tgt language terms.
    """

    def __init__(self, word2id=None):
        """ Init VocabEntry Instance.
        @param word2id (dict): dictionary mapping words 2 indices
        """
        if word2id:
            self.word2id = word2id
        else:
            self.word2id = dict()
            self.word2id['<pad>'] = 0  # Pad Token
            self.word2id['<s>'] = 1  # Start Token
            self.word2id['</s>'] = 2  # End Token
            self.word2id['<unk>'] = 3  # Unknown Token
        self.unk_id = self.word2id['<unk>']
        self.id2word = {v: k for k, v in self.word2id.items()}

        ## Additions to the A4 code:
        self.char_list = list(
            """ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789,;.!?:'\"/\\|_@#$%^&*~`+-=<>()[]""")

        self.char2id = dict()  # Converts characters to integers
        self.char2id['∏'] = 0  # <pad> token
        self.char2id['{'] = 1  # start of word token
        self.char2id['}'] = 2  # end of word token
        self.char2id['Û'] = 3  # <unk> token
        for i, c in enumerate(self.char_list):
            self.char2id[c] = len(self.char2id)
        self.char_pad = self.char2id['∏']
        self.char_unk = self.char2id['Û']
        self.start_of_word = self.char2id["{"]
        self.end_of_word = self.char2id["}"]
        assert self.start_of_word + 1 == self.end_of_word

        self.id2char = {v: k for k, v in self.char2id.items()}  # Converts integers to characters
        ## End additions to the A4 code

    def __getitem__(self, word):
        """ Retrieve word's index. Return the index for the unk
        token if the word is out of vocabulary.
        @param word (str): word to look up.
        @returns index (int): index of word
        """
        return self.word2id.get(word, self.unk_id)

    def __contains__(self, word):
        """ Check if word is captured by VocabEntry.
        @param word (str): word to look up
        @returns contains (bool): whether word is contained
        """
        return word in self.word2id

    def __setitem__(self, key, value):
        """ Raise error, if one tries to edit the VocabEntry.
        """
        raise ValueError('vocabulary is readonly')

    def __len__(self):
        """ Compute number of words in VocabEntry.
        @returns len (int): number of words in VocabEntry
        """
        return len(self.word2id)

    def __repr__(self):
        """ Representation of VocabEntry to be used
        when printing the object.
        """
        return 'Vocabulary[size=%d]' % len(self)

    def id2word(self, wid):
        """ Return mapping of index to word.
        @param wid (int): word index
        @returns word (str): word corresponding to index
        """
        return self.id2word[wid]

    def add(self, word):
        """ Add word to VocabEntry, if it is previously unseen.
        @param word (str): word to add to VocabEntry
        @return index (int): index that the word has been assigned
        """
        if word not in self:
            wid = self.word2id[word] = len(self)
            self.id2word[wid] = word
            return wid
        else:
            return self[word]

    def words2charindices(self, sents):
        """ Convert list of sentences of words into list of list of list of character indices.
        @param sents (list[list[str]]): sentence(s) in words
        @return word_ids (list[list[list[int]]]): sentence(s) in indices
        """
        return [[[self.char2id.get(c, self.char_unk) for c in ("{" + w + "}")] for w in s] for s in sents]

    def words2indices(self, sents):
        """ Convert list of sentences of words into list of list of indices.
        @param sents (list[list[str]]): sentence(s) in words
        @return word_ids (list[list[int]]): sentence(s) in indices
        """
        return [[self[w] for w in s] for s in sents]

    def indices2words(self, word_ids):
        """ Convert list of indices into words.
        @param word_ids (list[int]): list of word ids
        @return sents (list[str]): list of words
        """
        return [self.id2word[w_id] for w_id in word_ids]

    def to_input_tensor_char(self, sents: List[List[str]], device: torch.device) -> torch.Tensor:
        """ Convert list of sentences (words) into tensor with necessary padding for
        shorter sentences.

        @param sents (List[List[str]]): list of sentences (words)
        @param device: device on which to load the tensor, i.e. CPU or GPU

        @returns sents_var: tensor of (max_sentence_length, batch_size, max_word_length)
        """
        ### YOUR CODE HERE for part 1e
        ### TODO:
        ###     - Use `words2charindices()` from this file, which converts each character to its corresponding index in the
        ###       character-vocabulary.
        ###     - Use `pad_sents_char()` from utils.py, which pads all words to max_word_length of all words in the batch,
        ###       and pads all sentences to max length of all sentences in the batch. Read __init__ to see how to get
        ###       index of character-padding token
        ###     - Connect these two parts to convert the resulting padded sentences to a torch tensor.
        ### HINT:
        ###     - You may find .contiguous() useful after reshaping. Check the following links for more details:
        ###         https://pytorch.org/docs/stable/tensors.html#torch.Tensor.contiguous
        ###         https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view

        char_sents = self.words2charindices(sents)
        res = torch.tensor(pad_sents_char(char_sents, char_pad_token=self.char_pad)) #b, max_sent_len, max_word
        res = res.permute(1, 0, 2).contiguous() # max_sent_len, b, max_word

        return res
        ### END YOUR CODE

    def to_input_tensor(self, sents: List[List[str]], device: torch.device) -> torch.Tensor:
        """ Convert list of sentences (words) into tensor with necessary padding for 
        shorter sentences.

        @param sents (List[List[str]]): list of sentences (words)
        @param device: device on which to load the tesnor, i.e. CPU or GPU

        @returns sents_var: tensor of (max_sentence_length, batch_size)
        """
        word_ids = self.words2indices(sents)
        sents_t = pad_sents(word_ids, self['<pad>'])
        sents_var = torch.tensor(sents_t, dtype=torch.long, device=device)
        return torch.t(sents_var)

    @staticmethod
    def from_corpus(corpus, size, freq_cutoff=2):
        """ Given a corpus construct a Vocab Entry.
        @param corpus (list[str]): corpus of text produced by read_corpus function
        @param size (int): # of words in vocabulary
        @param freq_cutoff (int): if word occurs n < freq_cutoff times, drop the word
        @returns vocab_entry (VocabEntry): VocabEntry instance produced from provided corpus
        """
        vocab_entry = VocabEntry()
        word_freq = Counter(chain(*corpus))
        valid_words = [w for w, v in word_freq.items() if v >= freq_cutoff]
        print('number of word types: {}, number of word types w/ frequency >= {}: {}'
              .format(len(word_freq), freq_cutoff, len(valid_words)))
        top_k_words = sorted(valid_words, key=lambda w: word_freq[w], reverse=True)[:size]
        for word in top_k_words:
            vocab_entry.add(word)
        return vocab_entry


In [8]:
# char2id

In [9]:
def words2charindices(sents):
    """ Convert list of sentences of words into list of list of list of character indices.
    @param sents (list[list[str]]): sentence(s) in words
    @return word_ids (list[list[list[int]]]): sentence(s) in indices
    """
    return [[[char2id.get(c, char_unk) for c in ("{" + w + "}")] for w in s] for s in sents]


In [12]:
import json
char2id =json.load(open('./sanity_check_en_es_data/char_vocab_sanity_check.json', 'r'))

In [13]:
id2char = {v: k for k, v in char2id.items()}

In [14]:
input = torch.randn(2).unsqueeze(0)

In [15]:
import torch.nn as nn

In [26]:
x = torch.tensor([[[1., 1., 1., 1.],
              [-2, -2, -2., -2.]],
             [[2, 2, 1, 1],
              [0.5, 0.5, 0, 0]]], dtype=torch.float32)

In [27]:
print("input tensor shape:  ", x.size())
x = x.permute(0, 2, 1).contiguous()

input tensor shape:   torch.Size([2, 2, 4])


In [28]:
print("input tensor shape:  ", x.size())

input tensor shape:   torch.Size([2, 4, 2])


In [99]:
x = torch.randn(2, 6, 50)
xreshaped = x.permute(0, 2, 1)
xreshaped.shape

torch.Size([2, 50, 6])

In [100]:
xreshaped #(e_char=4, m_word=6)
b, e_char, m_word = xreshaped.size()

In [101]:
e_char

50

In [110]:
xconv = conv1d(xreshaped)

In [111]:
xconv.shape

torch.Size([2, 10, 4])

In [56]:
# m_word #6
# k # 5
# padding # 1
# 6-5+2+1 = 4

In [64]:
maxpool = nn.MaxPool1d(kernel_size=m_word+2*1-5+1)

In [65]:
xout = maxpool(xconv)

/Users/shaozhetao/miniconda3/envs/mlds/lib/python3.7/site-packages/torch/nn/functional.py:652: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1156.)
  return torch.max_pool1d(input, kernel_size, stride, padding, dilation, ceil_mode)


In [66]:
xout.shape

torch.Size([2, 10, 1])

In [60]:
xccc = F.relu(xconv)

In [61]:
xccc.shape

torch.Size([2, 10, 4])

In [108]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CS224N 2019-20: Homework 5
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class CNN(nn.Module):

    # Remember to delete the above 'pass' after your implementation
    ### YOUR CODE HERE for part 1g
    def __init__(self, e_char, filters, padding=1, kernel_size=5):
        super(CNN, self).__init__()

        self.e_char = e_char
        self.m_word = m_word
        self.filters = filters
        self.padding = padding
        self.k = kernel_size

        self.conv1d = None
        self.maxpool = None

        self.conv1d = nn.Conv1d(
            in_channels=self.e_char,
            out_channels=self.filters,
            kernel_size=self.k,
            stride=1,
            padding=self.padding,
            padding_mode='zeros',
            bias=True
        )



    def forward(self, xemb: torch.Tensor):
        # xemb #shape (batch, m_word, e_char)
        # xreshape #shape (batch, e_char, m_word)
        # W #shape (filter, e_char, k)

        m_word = xemb.shape[1]
        x_reshaped = xemb.permute(0, 2, 1)
        x_conv = self.conv1d(x_reshaped)
        x_conv = F.relu(x_conv)

        maxpool = nn.MaxPool1d(kernel_size=m_word + 2 * self.padding - self.k + 1)
        x_conv_out = maxpool(x_conv)

        return x_conv_out

    ### END YOUR CODE



In [138]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Highway(nn.Module):
    # Remember to delete the above 'pass' after your implementation
    ### YOUR CODE HERE for part 1f
    def __init__(self, eword_size):
        super(Highway, self).__init__()
        self.eword_size = eword_size

        self.w_proj = nn.Linear(self.eword_size, self.eword_size, bias=True)
        # self.b_proj = None
        self.w_gate = nn.Linear(self.eword_size, self.eword_size, bias=True)
        # self.b_gate = None
        self.highway_ReLU = nn.ReLU()

    def forward(self, x_conv: torch.Tensor):
        x_proj_pre = self.w_proj(x_conv)
        x_proj = self.highway_ReLU(x_proj_pre)
        x_gate_pre = self.w_gate(x_proj)
        x_gate = F.sigmoid(x_gate_pre)

        x_highway = x_gate*x_proj + (1-x_gate)*x_conv

        return x_highway

In [143]:
x = torch.randn(6, 4)#.unsqueeze(0)

In [144]:
x.shape

torch.Size([6, 4])

In [140]:
# eword_size = 4
# w_proj = nn.Linear(eword_size, eword_size, bias=True)
# w_gate = nn.Linear(eword_size, eword_size, bias=True)
# highway_ReLU = nn.ReLU()

# x_conv = x
# x_proj_pre = w_proj(x_conv)
# x_proj = highway_ReLU(x_proj_pre)
# x_gate_pre = w_gate(x_proj)
# x_gate = F.sigmoid(x_gate_pre)

In [137]:
x_proj*x_gate

tensor([[0.0000, 0.5411, 0.0000, 0.0000]], grad_fn=<MulBackward0>)

In [135]:
torch.bmm(x_gate, x_proj)

RuntimeError: Expected 3-dimensional tensor, but got 2-dimensional tensor for argument #1 'batch1' (while checking arguments for bmm)

In [132]:
x_gate

tensor([[0.5705, 0.5203, 0.5695, 0.5528]], grad_fn=<SigmoidBackward>)

In [145]:
hh = Highway(eword_size=4)

In [146]:
hh(x)

tensor([[ 1.3054, -0.0800, -0.6386, -0.5675],
        [ 0.4913,  0.9047,  0.5233,  0.1609],
        [ 0.4192,  0.2976, -0.3603, -0.1999],
        [-0.0752,  0.5150,  1.0933,  0.3429],
        [ 0.6722,  0.1355, -0.4967,  0.1334],
        [-0.2583, -0.0197,  0.5127,  0.1623]], grad_fn=<AddBackward0>)

In [78]:
# yy = torch.t(yy)#.shape # [b, max_sent_len, max_word]

In [66]:
yy.shape

torch.Size([5, 40, 16])

In [70]:
yy

tensor([[[ 1, 15, 30,  ...,  0,  0,  0],
         [ 1, 41, 41,  ...,  0,  0,  0],
         [ 1, 33, 34,  ...,  0,  0,  0],
         ...,
         [ 1, 58, 56,  ...,  0,  0,  0],
         [ 1, 30, 44,  ...,  0,  0,  0],
         [ 1, 68,  2,  ...,  0,  0,  0]],

        [[ 1, 15, 44,  ...,  0,  0,  0],
         [ 1, 43, 38,  ...,  0,  0,  0],
         [ 1, 43, 44,  ...,  0,  0,  0],
         ...,
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0]],

        [[ 1, 15, 44,  ...,  0,  0,  0],
         [ 1, 31, 34,  ...,  0,  0,  0],
         [ 1, 33, 34,  ...,  0,  0,  0],
         ...,
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0]],

        [[ 1, 19, 34,  ...,  0,  0,  0],
         [ 1, 43, 44,  ...,  0,  0,  0],
         [ 1, 34, 48,  ...,  0,  0,  0],
         ...,
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0, 

In [75]:
yy.permute((1,0,2)).contiguous()

tensor([[[ 1, 15, 30,  ...,  0,  0,  0],
         [ 1, 15, 44,  ...,  0,  0,  0],
         [ 1, 15, 44,  ...,  0,  0,  0],
         [ 1, 19, 34,  ...,  0,  0,  0],
         [ 1,  6, 44,  ...,  0,  0,  0]],

        [[ 1, 41, 41,  ...,  0,  0,  0],
         [ 1, 43, 38,  ...,  0,  0,  0],
         [ 1, 31, 34,  ...,  0,  0,  0],
         [ 1, 43, 44,  ...,  0,  0,  0],
         [ 1, 42, 50,  ...,  0,  0,  0]],

        [[ 1, 33, 34,  ...,  0,  0,  0],
         [ 1, 43, 44,  ...,  0,  0,  0],
         [ 1, 33, 34,  ...,  0,  0,  0],
         [ 1, 34, 48,  ...,  0,  0,  0],
         [ 1, 43, 42,  ...,  0,  0,  0]],

        ...,

        [[ 1, 58, 56,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0]],

        [[ 1, 30, 44,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,

In [28]:
ss = src_sents
max_word_length = max(len(w) for s in ss for w in s )

max_sent_len = max(len(s) for s in ss)

In [19]:
xx[1]

[['l'],
 ['l'],
 ['e'],
 ['g'],
 ['a'],
 ['d'],
 ['a'],
 ['sss'],
 ['sss'],
 ['sss'],
 ['sss'],
 ['sss'],
 ['sss'],
 ['sss']]